### ISSUE TITLE
useMemo

### ISSUE THREAD

**Issue by suminc7** [kobevino/beer-toy-project#2]
https://github.com/jason0853/beer-toy-project/blob/816d3909aa91dfb393a9fbf777771e25e4ce8df2/beer-frontend/src/components/PurchaseList/index.tsx#L34

hooks에 useMemo 사용해보면 좋을 것 같아용
리렌더링시에 계속 계산할테니~ 
mobx에선 computed

**Comment by jason0853** [comment]
> https://github.com/jason0853/beer-toy-project/blob/816d3909aa91dfb393a9fbf777771e25e4ce8df2/beer-frontend/src/components/PurchaseList/index.tsx#L34
> 
> hooks에 useMemo 사용해보면 좋을 것 같아용
> 리렌더링시에 계속 계산할테니~
> mobx에선 computed
